---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tutorial-deployment
  namespace: tutorial
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tutorial
    spec:
      containers:
      - name: tutorial
        image: ${DOCKER_REGISTRY}/tutorial:v0.0.7
        envFrom:
        - configMapRef:
            name: tutorial-config
        env:
        - name: TUTORIAL_SECRET
          valueFrom:
            secretKeyRef:
              name: tutorial-secret
              key: secret
