---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tutorial-deployment
  namespace: tutorial
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tutorial
    spec:
      containers:
      - name: tutorial
        image: ${DOCKER_REGISTRY}/tutorial:v0.0.11
        envFrom:
        - configMapRef:
            name: tutorial-config
        env:
        - name: TUTORIAL_SECRET
          valueFrom:
            secretKeyRef:
              name: tutorial-secret
              key: secret
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
        livenessProbe:
          httpGet:
            path: /ready
            port: 8000
        volumeMounts:
        - mountPath: "/data"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: tutorial-disk
