---
apiVersion: v1
kind: Service
metadata:
  name: tutorial-service
  namespace: tutorial
  labels:
    app: tutorial
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 8000
  selector:
    app: tutorial
